os: linux
dist: focal
language: shell
env: 
  global:
   # - FOO=a
    - BAR=false
install: skip
stages:
  - name: A
    if: env(BAR) = false
  - name: B
    if: env(BAR) = true
jobs: 
  include:
    - stage: "A"
      name: "STAGEA JOB1"
      script: sleep 1

    - stage: "A"
      name: "STAGE A JOB 2"
      script: sleep 2

    - stage: "B"
      name: "STAGE B JOB 1"
      script: sleep 3

    - stage: "B"
      name: "STAGE B JOB2"
      script: sleep 4
